subset:
  name: prior_reading__student
  include_groups:
    - Baseline
    - pTarget
  exclude_groups: []
load:
  enabled: true # set to true to load existing results
  run_id: 2026-01-22_121654__prior_reading__student   # e.g. "2026-01-22_121654__prior_reading__student"