subset:
  name: prior_reading__student__teacher
  include_groups:
    - Baseline
    - pTarget
    - pCourseClass
  exclude_groups: []
load:
  enabled: false # set to true to load existing results
  run_id: null   # e.g. "2026-01-22_121713__prior_reading__student__teacher"
  # enabled: true # set to true to load existing results
  # run_id: 2026-01-22_121713__prior_reading__student__teacher   