subset:
  name: prior_reading__student__home
  include_groups:
    - Baseline
    - Student
    - Home
  exclude_groups: []
load:
  enabled: false # set to true to load existing results
  run_id: null   # e.g. "2026-01-22_121706__prior_reading__student__home"
  # enabled: true # set to true to load existing results
  # run_id: 2026-01-26_173957__prior_reading__student__home   